
module Rozi

  ##
  # A list of datums accepted by Ozi Explorer.
  #
  DATUMS = [
    "Adindan",
    "Afgooye",
    "Ain el Abd 1970",
    "Anna 1 Astro 1965",
    "Arc 1950",
    "Arc 1960",
    "Ascension Island 1958",
    "Astro B4 Sorol Atoll",
    "Astro Beacon 1945",
    "Astro DOS 71/4",
    "Astronomic Stn 1952",
    "Australian Geodetic 1966",
    "Australian Geodetic 1984",
    "Australian Geocentric 1994 (GDA94)",
    "Austrian",
    "Bellevue (IGN)",
    "Bermuda 1957",
    "Bogota Observatory",
    "Campo Inchauspe",
    "Canton Astro 1966",
    "Cape",
    "Cape Canaveral",
    "Carthage",
    "CH-1903",
    "Chatham 1971",
    "Chua Astro",
    "Corrego Alegre",
    "Djakarta (Batavia)",
    "DOS 1968",
    "Easter Island 1967",
    "Egypt",
    "European 1950",
    "European 1950 (Mean France)",
    "European 1950 (Spain and Portugal)",
    "European 1979",
    "Finland Hayford",
    "Gandajika Base",
    "Geodetic Datum 1949",
    "Guam 1963",
    "GUX 1 Astro",
    "Hartebeeshoek94",
    "Hermannskogel",
    "Hjorsey 1955",
    "Hong Kong 1963",
    "Hu-Tzu-Shan",
    "Indian Bangladesh",
    "Indian Thailand",
    "Israeli",
    "Ireland 1965",
    "ISTS 073 Astro 1969",
    "Johnston Island",
    "Kandawala",
    "Kerguelen Island",
    "Kertau 1948",
    "L.C. 5 Astro",
    "Liberia 1964",
    "Luzon Mindanao",
    "Luzon Philippines",
    "Mahe 1971",
    "Marco Astro",
    "Massawa",
    "Merchich",
    "Midway Astro 1961",
    "Minna",
    "NAD27 Alaska",
    "NAD27 Bahamas",
    "NAD27 Canada",
    "NAD27 Canal Zone",
    "NAD27 Caribbean",
    "NAD27 Central",
    "NAD27 CONUS",
    "NAD27 Cuba",
    "NAD27 Greenland",
    "NAD27 Mexico",
    "NAD27 San Salvador",
    "NAD83",
    "Nahrwn Masirah Ilnd",
    "Nahrwn Saudi Arbia",
    "Nahrwn United Arab",
    "Naparima BWI",
    "NGO1948",
    "NTF France",
    "Norsk",
    "Observatorio 1966",
    "Old Egyptian",
    "Old Hawaiian",
    "Oman",
    "Ord Srvy Grt Britn",
    "Pico De Las Nieves",
    "Pitcairn Astro 1967",
    "Potsdam Rauenberg DHDN",
    "Prov So Amrican 1956",
    "Prov So Chilean 1963",
    "Puerto Rico",
    "Pulkovo 1942 (1)",
    "Pulkovo 1942 (2)",
    "Qatar National",
    "Qornoq",
    "Reunion",
    "Rijksdriehoeksmeting",
    "Rome 1940",
    "RT 90",
    "S42       ",
    "Santo (DOS)",
    "Sao Braz",
    "Sapper Hill 1943",
    "Schwarzeck",
    "South American 1969",
    "South Asia",
    "Southeast Base",
    "Southwest Base",
    "Timbalai 1948",
    "Tokyo",
    "Tristan Astro 1968",
    "Viti Levu 1916",
    "Wake-Eniwetok 1960",
    "WGS 72",
    "WGS 84",
    "Yacare",
    "Zanderij"
  ]

end
